eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:    
    eviction-interval-timer-in-ms: 500000
    enable-self-preservation: false
spring:
  application:
    name: eureka-server
    